### ISSUE TITLE
Subsetting samples and columns of a MethyLumiSet subsets QC probes

### ISSUE THREAD

**Issue by Alanocallaghan** [seandavi/methylumi#21]
Loading 450k methylation data as follows: 
`methyset <- methylumIDAT(barcodes=barcodes, idatPath="./data/IDATS")`

Then the following code will error (subscript out of bounds): 
`methyset[1:1000, 1:2]`

This is because there are only 850 QC probes, which should not be subset with the indices used on the main dataset.

The code responsible is below: 
https://github.com/seandavi/methylumi/blob/master/R/MethyLumiSet-class.R#L454

I've also raised this on Bioconductor:
https://support.bioconductor.org/p/102421/

**Comment by seandavi** [comment]
Thx, @Alanocallaghan! Little rusty, it seems. New versions are 2.24.2 and 2.25.2.
